config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :bloggers, skip: [:sessions]
  as :blogger do
    get 'login', to: 'devise/sessions#new', as: :new_blogger_session
    post 'login', to: 'devise/sessions#create', as: :blogger_session
    get 'logout', to: 'devise/sessions#destroy', as: :destroy_blogger_session
  end

  root 'articles#index'
  resources :articles, only: [:show] do
    resources :comments, only: [:create]
  end

  get 'bio' => 'pages#bio'
  get 'about' => 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :blogger
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true

  scope :order_by_recent, -> { order(created_at: :desc) }

  def self.random_article
    find(pluck(:id).sample)
  end

  # Label is not hidden, need to fix
  rails_admin do
    edit do
      configure :blogger_id do
        help ""
        label :hidden => true

        default_value do
          bindings[:view].current_blogger.id
        end

        view_helper do
          :hidden_field
        end
      end
    end
  end
end

app/models/blogger.rb
class Blogger < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :validatable
  has_many :articles
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  before_create :random_avatar_path
  belongs_to :article

  validates :content, presence: true

  scope :order_by_recent, -> { order(created_at: :desc) }

  private

  def random_avatar_path
    self.avatar_path = "comments/avatar_#{rand(1..7)}.png"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.order_by_recent.page(params[:page]).per(5)
  end

  def show
    @article = Article.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    article = Article.find(params[:article_id])
    comment = article.comments.build(article_params)

    if comment.save
      flash[:success] = 'Comment is successfully created'
    else
      flash[:alert] = 'Something went wrong. PLease try again later'
    end

    redirect_to article_path(article)
  end

  private

  def article_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def bio
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def random_article
    Article.random_article
  end
end

app/views/articles/_article.html.erb
<div class="post-preview">
  <%= link_to article_path(article.id) do %>
    <h2 class="post-title"><%= article.title %></h2>
    <h3 class="post-subtitle"><%= article.content.truncate(65) %></h3>
  <% end %>

  <p class="post-meta">Posted by <%= article.blogger.name %> on
    <%= article.created_at.strftime("%d %b. %Y") %>
  </p>
</div>

app/views/articles/index.html.erb
<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

      <div class="articles-list">
        <% @articles.each do |article| %>
            <%= render article %>
        <% end %>
      </div>

      <%= paginate @articles %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="post-preview">
        <h2 class="post-title text-center"><%= @article.title %></h2>
        <p><%= @article.content.html_safe %></p>
      </div>
      <%= render 'comments/form' %>

      <% if @article.comments.any? %>
          <div class="text-center">
            <h3>Comments (<%= @article.comments.count %>)</h3>
          </div>
          <br/>
          <%= render partial: 'comments/comments_list', locals: { comments: @article.comments} %>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/_comment.html.erb
<div class="comment">
  <div class="comment-header">
    <%= image_tag(comment.avatar_path, class: 'comment-avatar')%>
  </div>

  <div class="comment-content">
    <%= comment.content %>
  </div>
</div>

app/views/comments/_comments_list.html.erb
<ul class="comments-list list-unstyled">
  <% comments.each do |comment| %>
      <% if comment.persisted? %>
          <li>
            <%= render comment %>
          </li>
      <% end %>
  <% end %>
</ul>

app/views/comments/_form.html.erb
<div id='comment-form' class="row">
  <div class="col-sm-3">
    <div class="oval"></div>
  </div>
  <div class="col-sm-6">
    <%= form_for([@article, @article.comments.build]) do |f| %>
        <div class="form-group">
          <%= f.text_area :content, rows: 3, placeholder: 'Share your thoughts...', class: 'form-control' %>
        </div>

        <%= f.submit 'Leave a comment', class: 'btn btn-primary btn-block'%>
    <% end %>
  </div>
  <div class="col-sm-3">
    <div class="oval"></div>
  </div>
</div>

app/views/layouts/_content_header.html.erb
<!-- Page Header -->
<header class="intro-header">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="site-heading">
          <h1>Ordinary Mortal's Blog</h1>
          <hr class="small">
          <span class="subheading">Everyday life logs</span>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_footer.html.erb
<hr/>
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <ul class="list-inline text-center">
          <li>
            <%= link_to('https://www.linkedin.com/in/maxym-tesliuk-35a10717a/', title: 'LinkedIn') do %>
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
              </span>
            <% end %>
          </li>

          <li>
            <%= link_to('https://www.facebook.com/maxym.tesliuk', title: 'Facebook') do %>
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
              </span>
            <% end %>
          </li>

          <li>
            <%= link_to('https://www.instagram.com/ordinarymortal/', title: 'Instagram') do %>
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
              </span>
            <% end %>
          </li>

          <li>
            <%= link_to('https://soundcloud.com/user-497787198', title: 'SoundCloud') do %>
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-soundcloud fa-stack-1x fa-inverse"></i>
              </span>
            <% end %>
          </li>
        </ul>

        <p class="copyright text-muted">Copyright &copy; Ordinary Mortal 2019</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        Menu <i class="fa fa-bars"></i>
      </button>
      <%= link_to 'Random Article', article_path(random_article), class: 'navbar-brand' if Article.any? %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to 'Home', root_path %>
        </li>
        <li>
          <%= link_to 'Bio', bio_path %>
        </li>
        <li>
          <%= link_to 'About', about_path %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>

    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-controller="<%= controller_name %>" data-action="<%= action_name %>">
    <%= render 'layouts/header' %>

    <div class="content-container">
      <%= render "layouts/content_header" %>

      <% flash.each do |msg_type, msg| %>
          <div class="alert text-center alert-<%= msg_type %>"><%= msg %></div>
      <% end %>

      <div class="content">
        <%= yield %>
      </div>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h1 class="text-center">About</h1>
      <p>
        Owning a personal blog is so valuable nowadays.
        Especially if you are a beginning developer.
        It is good for coding practice, it serves as a resume, it helps learning new technologies.
      </p>

      <p>
        While creating this blog what I really liked the most is planning.
        I planned every single step and wrote all down.
        It is so satisfying (even though I didn't always stick to the plan) to have everything prepared.
      </p>

      <p>
        In this blog I am going to have articles both about my learning progress
        and some real life experiences (or maybe not).
      </p>
    </div>
  </div>
</div>

app/views/pages/bio.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h1 class="text-center">Bio</h1>

      <p>
        Hello, my name is FirstName LastName and I am the developer/designer/founder/creator/author...
        <br>
        I can SkillName and also good at SkillName...
      </p>

      <p>That's how most of bios begin, I guess. So lets start.</p>

      <p>
        People usually call me Max (that's my real name actually).
        I am a 21 y.o. Ukrainian student. I study computer science at the Academy of Printing in Lviv, Ukraine.
      </p>

      <p>
        As a child I really enjoyed learning languages
        (watched movies, played video games in English despite the fact I barely understood anything).
        Now I can somehow express thoughts in English (a bit German and Polish).
        I like web development because I always wanted my job to be creative.
        You can implement a feature in many different ways.
        I enjoy making new things and finding new ways to make things work.
      </p>

      <p>
        After reading tons of bios I feel like I need to mention some valuable achievements or experiences.
        So don't forget to water your houseplants (well, this is my very first bio).
        I've got no serious professional experience yet but feel like moved pretty far
        as Ruby on Rails developer while creating this blog and other apps.
      </p>
    </div>
  </div>
</div>